DELETE
FROM genre
WHERE name IN (
       'Pop',
       'Rock',
       'Hip Hop',
       'Jazz',
       'Classic Rock',
       'Country',
       'Blues',
       'R&B',
       'Electronic',
       'Dance',
       'Indie',
       'Folk',
       'Heavy Metal',
       'Punk',
       'Soul',
       'Reggae',
       'Classical',
       'Alternative',
       'Funk',
       'Disco',
       'House',
       'Techno',
       'Trance',
       'K-Pop',
       'Latin',
       'Reggaeton',
       'Ska',
       'Gospel',
       'Swing',
       'Grime',
       'Dubstep',
       'Ambient',
       'Singer-Songwriter',
       'Instrumental',
       'Soundtrack',
       'Other',
       'Games',
       'Anime'
    );
