INSERT INTO genre (name)
VALUES ('Pop'),
       ('Rock'),
       ('Hip Hop'),
       ('Jazz'),
       ('Classic Rock'),
       ('Country'),
       ('Blues'),
       ('R&B'),
       ('Electronic'),
       ('Dance'),
       ('Indie'),
       ('Folk'),
       ('Heavy Metal'),
       ('Punk'),
       ('Soul'),
       ('Reggae'),
       ('Classical'),
       ('Alternative'),
       ('Funk'),
       ('Disco'),
       ('House'),
       ('Techno'),
       ('Trance'),
       ('K-Pop'),
       ('Latin'),
       ('Reggaeton'),
       ('Ska'),
       ('Gospel'),
       ('Swing'),
       ('Grime'),
       ('Dubstep'),
       ('Ambient'),
       ('Singer-Songwriter'),
       ('Instrumental'),
       ('Soundtrack'),
       ('Games'),
       ('Anime'),
       ('Other');