-- Up Migration
INSERT INTO instrument (name) VALUES
  ('Harp'),
  ('Lute'),
  ('Fiddle'),
  ('Violin'),
  ('Viola'),
  ('Cello'),
  ('Double Bass'),
  ('Electric Guitar'),
  ('Flute'),
  ('Oboe'),
  ('Clarinet'),
  ('Fife'),
  ('Panpipes'),
  ('Saxophone'),
  ('Trumpet'),
  ('Trombone'),
  ('Tuba'),
  ('Horn'),
  ('Piano'),
  ('Timpani'),
  ('Bongo'),
  ('Bass Drum'),
  ('Snare Drum'),
  ('Cymbal');
